project:
  type: website
  output-dir: docs

website:
  title: "Henrique Schall"
  navbar:
    left:
      - skills.qmd

format:
  html:
    theme:
      - Cyborg
      - brand
    css: styles.css
    toc: true



